version: "3.7"

services:
  app1:
    container_name: app1
    build: app1/
    ports:
      - 3000:3000
  app2:
    container_name: app2
    build: app2/
    ports:
      - 3001:3001
    depends_on:
      - app1
